### ISSUE TITLE
configuration file macrodefinition with value produces error message

### ISSUE THREAD

**Issue by mhallivu** [standardese/standardese#243] opened 2023-10-20 04:19 UTC
Macro definition like
[compilation]
macro_definition="R0_CRITICAL_DUMPED_RECORDS_LOCATION=0x76fad868"

Produces error like:
[libclang] [error] <command line>:5: macro name must be an identifier

Value however seems to be used

**Comment by saraedum** [comment] 2023-11-02 20:50
standardese uses boost's program_options to parse the config file. I don't think that the implementation supports quoting at least it's not mentioned here: https://www.boost.org/doc/libs/1_83_0/doc/html/program_options/overview.html#id-1.3.30.5.10

Does it work if you remove the quotes?

**Comment by mhallivu** [comment] 2023-11-03 04:32
No, it does not. It will complain that file does not existentiaaliselta for the value partSent from my iPhoneOn Nov 2, 2023, at 22:50, Julian Rüth ***@***.***> wrote:﻿
standardese uses boost's program_options to parse the config file. I don't think that the implementation supports quoting at least it's not mentioned here: https://www.boost.org/doc/libs/1_83_0/doc/html/program_options/overview.html#id-1.3.30.5.10
Does it work if you remove the quotes?

**Comment by saraedum** [comment] 2023-11-04 19:02
> No, it does not. It will complain that file does not existentiaaliselta for the value part

Sorry, I don't understand what you are trying to write. It works for me without the quotes.

**Comment by mhallivu** [comment] 2023-11-04 21:04
I gave up standardese and started to use oxygen. For pure c it is currently better alternative. There is very little activity regarding standardese, so it evidently is not going forward.Sent from my iPhoneOn Nov 4, 2023, at 21:02, Julian Rüth ***@***.***> wrote:﻿

No, it does not. It will complain that file does not existentiaaliselta for the value part

Sorry, I don't understand what you are trying to write. It works for me without the quotes.

**Comment by saraedum** [comment] 2023-11-05 10:16
You mean doxygen I suppose?

> There is very little activity regarding standardese

That's true.

I am closing this issue. I cannot reproduce the problem you have. It works fine for me once I drop the quotes. Feel free to reopen.

**Closed by saraedum** 2023-11-05 10:16 UTC
