### ISSUE TITLE
standardese 0.5.0 test failure

### ISSUE THREAD

**Issue by chenrui333** [standardese/standardese#188] opened 2021-03-18 13:32 UTC
👋 trying to build the latest release, but run into some build issue.

relates to https://github.com/Homebrew/homebrew-core/pull/73349

**Comment by carlocab** [comment] 2021-03-18 18:18
More details on this. To test the build, we run the following command, and its output follows.
```
==> standardese --compilation.standard c++17 --output.format xml /private/tmp/standardese-test-20210318-21843-1nstw7t/test.hpp
dyld: Library not loaded: @rpath/libstandardese.dylib
  Referenced from: /usr/local/bin/standardese
  Reason: image not found
Error: standardese: failed
```
We use CMake to build and install with
```
cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$prefix
cmake --build build
cmake --install build
```
The difficulty seems to be is that this doesn't install the library that `standardese` is looking for.

**Comment by carlocab** [comment] 2021-03-19 03:13
Looking into this some more, it seems like `standardese` has linkage with libraries that are never installed:
```
❯ otool -L standardese
standardese:
        @rpath/libstandardese.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/local/opt/boost/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/local/opt/boost/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/local/opt/boost/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/libcppast.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/lib_cppast_tiny_process.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/local/opt/llvm/lib/libclang.dylib (compatibility version 1.0.0, current version 11.1.0)
        /usr/local/opt/llvm/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```
If `standardese` needs these libraries, then surely the install target should put them in the right place?

**Comment by saraedum** [comment] 2021-03-21 20:02
@carlocab, I found the same when trying to build this for conda-forge. The install does not work properly when building with shared libraries #186.

It's currently the best to disable shared libraries until #186 has been fixed as in https://github.com/conda-forge/standardese-feedstock/blob/master/recipe/build.sh#L9. This restores the previous behavior.

**Comment by saraedum** [comment] 2021-03-21 20:04
It appears you found another work around by manually installing the dependencies. I'll close this as it is a (non-obvious) duplicate of #186.

**Closed by saraedum** 2021-03-21 20:04 UTC
